---
#
# Common handlers to restart services
#
- name: restart apache
  action: service name=apache2 state=restarted
  become: yes

- name: restart mysql
  action: service name=mysql state=restarted
  become: yes

- name: reload nfs
  action: command invoke-rc.d nfs-kernel-server restart
  become: yes

- name: restart ssh
  action: service name=ssh state=restarted
  become: yes

- name: restart exim4
  action: service name=exim4 state=restarted
  become: yes

- name: Update apt-get
  action: apt update_cache=yes  
  become: yes

- name: restart nbd
  action: service name=nbd-server state=restarted
  become: yes

# RAID
- name: restart mdm
  action: service name=mdm state=restarted
  become: yes

# LOCALES
- name: rebuild locales
  command: /usr/sbin/locale-gen
  become: yes

# handlers file for locale.gen
- name: generate locales
  command: locale-gen
  become: yes
