---
#
# Common handlers to restart services
#
- name: restart apache
  action: service name=apache2 state=restarted

- name: restart mysql
  action: service name=mysql state=restarted

- name: reload nfs
  action: command invoke-rc.d nfs-kernel-server restart

- name: restart ssh
  action: service name=ssh state=restarted
