---
#
# Media center
#
# This builds a media center & office machine using XBMC & LTSP. At the end you should have 
# the following.
# - Main server with XBMC and lots of software for work, rest and play
#
# 
# Version: 1.9
# Tested OS: Linux Mint Debian Edition (rolling release)
# Command: ansible-playbook -K bender.yml
#
- hosts: home_server
  user: xbmc
  sudo: yes
  vars:
    password: $1$SomeSalt$nbQMcEVhuIZWc9xDaQOs70
  vars_files:
    - "vars/defaults.yml"
    - "vars/$ansible_distribution-$ansible_architecture.yml"
    - "vars/$ansible_distribution.yml"
    - "vars/Debian-testing.yml"

  # Tasks for XBMC are put in a specific order
  tasks:
    # Add xbmc user
    - name: Add {{ main_user }} user
      user: name={{ main_user }} password={{ password }} groups='sudo' shell=/bin/bash

    - include: common/tasks/system.yml
    - include: common/tasks/samba.yml
    - include: common/tasks/apache.yml 
    - include: common/tasks/php.yml
    - include: common/tasks/office.yml 
    - include: common/tasks/xbmc.yml
    - include: common/tasks/gnome-do.yml
    - include: common/tasks/ltsp.yml
    - include: common/tasks/ltsp-build.yml
    
    # Remarked out DHCP until we fix the issue with starting it
    - include: common/tasks/ltsp-dhcpd.yml
    
    - include: common/tasks/nvidia.yml
    - include: common/tasks/lvm.yml
    - include: common/tasks/x2go.yml

    - include: common/tasks/dropbox.yml
    - include: common/tasks/mozilla.yml

    - include: common/tasks/emacs.yml
    - include: common/tasks/rbenv.yml
    - include: common/tasks/rails.yml



  handlers:
    - include: common/handlers/handlers.yml
