---
#
# Media center
# Tested on: Debian 9 Stretch
# Updated & tested: 11/07/2017
#
# This builds a media center using Kodi, tvheadend & LTSP. At the end you should have the following
# - Main server with Kodi and lots of software for work, rest and play
# - Fat clients booting from the main server with Kodi & some software for basic browsing/email.
#
# Run
# ansible-playbook media_center.yml -b -v
# -b become sudo
# -v verbose
#
- hosts: media-servers
  user: kodi
  sudo: yes
  vars_files:
    - "vars/defaults.yml"
    - "vars/$ansible_distribution-$ansible_architecture.yml"
    - "vars/$ansible_distribution.yml"
    - "vars/custom.yml"

  # Tasks for XBMC are put in a specific order
  tasks:
    # Install system tools
    - include: common/tasks/add_testing_repo.yml
    - include: common/tasks/system.yml
    - include: common/tasks/system-gui.yml
    - include: common/tasks/email.yml
    - include: common/tasks/ruby.yml
    - include: common/tasks/backup.yml
    - include: common/tasks/dropbox.yml

    # Install multimedia and thin clients
    - include: common/tasks/kodi.yml
    - include: common/tasks/ltsp.yml
    - include: common/tasks/ltsp-fat-client.yml
    - include: common/tasks/ltsp-build.yml
    - include: common/tasks/tvheadend.yml

    # Install office and admin related software
    - include: common/tasks/office.yml 
    - include: common/tasks/x2go.yml

  handlers:
    - include: common/handlers/handlers.yml
