---
#
# Webserver for running Ruby on Rails with postgresql & node.
#
# Run
# ansible-playbook webserver.yml -b -v
# -b become sudo
# -v verbose

- hosts: dev-notebook
  user: dev
  become: yes
  connection: ssh # or paramiko
  vars:
    repo: testing
    gituser: drej2k
    monitor_1: "HDMI2"
    monitor_2: "eDP1"
    monitor_orientation: "--left-of"
    output_mode: "--auto"
    emacs_user_config_github: 'https://github.com/drej2k/emacs-config.git'
    oh_my_zsh:
      theme: robbyrussell
      plugins: git
      update_days: 13
    locale: "en_AU.UTF-8"
      case_sensitive: true
      hyphen_insensitive: true
      disable_update_prompt: true
      disable_auto_update: true
      disable_ls_colors: true
      disable_auto_title: true
      disable_untracked_files_dirty: true
      disable_correction: true
      completion_waiting_dots: false

  vars_files:
    - "vars/defaults.yml"
    - "vars/{{ ansible_distribution }}-{{ ansible_architecture }}.yml"
    - "vars/{{ ansible_distribution }}.yml"

  pre_tasks:
    - include: common/tasks/add_repositories.yml
      become: yes

  tasks:
    - include: common/tasks/system.yml
      become: yes
    - include: common/tasks/postgresql.yml
      become: yes
    - include: common/tasks/email-server.yml
      become: yes
    - include: common/tasks/ruby.yml # Install a system ruby used with backup
    - include: common/tasks/programming.yml 
    - include: common/tasks/backup.yml
    - include: common/tasks/locale.yml
    - include: common/tasks/emacs.yml
    - include: common/tasks/office.yml 
    - include: common/tasks/lvm.yml
    - include: common/tasks/x2go.yml      
    - include: common/tasks/exwm-config.yml
    - include: common/tasks/node-dev-machine.yml
    - include: common/tasks/yarn.yml
    - include: common/tasks/zsh.yml
    - include: common/tasks/rbenv.yml
    - include: common/tasks/rails.yml
    - include: common/tasks/compression-tools.yml
    - include: common/tasks/custom-software.yml      
    - include: common/tasks/kvm.yml
    - include: common/tasks/virtual-box.yml
  handlers:
    - include: common/handlers/handlers.yml

