---
#
# Office system
#
# My office system which runs thin clients and is setup for these firms Accountants, Lawyers, Real Estate &
# Programmers. It uses thin clients and the server has nvidia graphics cards.
#

- hosts: ltsp_thin
  user: map7
  sudo: yes
  vars:
    main_user: map7
  vars_files:
    - "vars/defaults.yml"
    - "vars/$ansible_distribution-$ansible_architecture.yml"
    - "vars/$ansible_distribution.yml"

  tasks:
    - include: common/tasks/system.yml
    - include: common/tasks/office.yml
    - include: common/tasks/auskey.yml
    - include: common/tasks/programming.yml 
    - include: common/tasks/ltsp.yml
    - include: common/tasks/ltsp-build.yml
    - include: common/tasks/nvidia.yml
