# Install ansible-galaxy roles using this file
#
# Run
# ansible-galaxy install -r requirements.yml
#
# Ref: https://docs.ansible.com/ansible/galaxy.html#installing-multiple-roles-from-a-file

# NodeJS
- src: Heroqu.nodejs4x