# Install ansible-galaxy roles using this file
#
# Run
# sudo ansible-galaxy install -r requirements.yml
#
# Ref: https://docs.ansible.com/ansible/galaxy.html#installing-multiple-roles-from-a-file

# Passenger
- src: mtpereira.passenger

# rbenv
- name: zzet.rbenv
  src: https://github.com/zzet/ansible-rbenv-role
