---
#
# Webserver for running Ruby on Rails with postgresql & node.
#

- hosts: webservers
  user: map7
  sudo: yes
  vars:
    main_user: map7
  vars_files:
    - "vars/defaults.yml"
    - "vars/$ansible_distribution-$ansible_architecture.yml"
    - "vars/$ansible_distribution.yml"
    - "vars/custom.yml"

  tasks:
    - include: common/tasks/system.yml
    - include: common/tasks/rbenv.yml
    - include: common/tasks/node.yml
    - include: common/tasks/rails.yml
    - include: common/tasks/apache.yml
    - include: common/tasks/postgresql.yml

  handlers:
    - include: common/handlers/handlers.yml