---
#
# Add commonly used repositories
#
- name: Add python-software-properties
  apt: pkg=python-software-properties force=yes update_cache=yes state=installed

- name: Remove cdrom source
  command: /bin/sed -i 's/^deb cdrom/#deb cdrom/g' /etc/apt/sources.list
  
- name: Add multimedia wheezy repository
  apt_repository: repo='deb http://www.deb-multimedia.org wheezy main non-free'
  when_string: $ansible_distribution == "Debian"

- name: Add contrib & non-free to main
  lineinfile:
    dest=/etc/apt/sources.list
    backrefs=yes
    regexp='deb http://ftp.au.debian.org/debian/ wheezy main$'
    line='deb http://ftp.au.debian.org/debian/ wheezy main contrib non-free'

- name: Add contrib & non-free to main src
  lineinfile:
    dest=/etc/apt/sources.list
    backrefs=yes
    regexp='deb-src http://ftp.au.debian.org/debian/ wheezy main$'
    line='deb-src http://ftp.au.debian.org/debian/ wheezy main contrib non-free'

- name: Add contrib & non-free to security
  lineinfile:
    dest=/etc/apt/sources.list
    backrefs=yes
    regexp='deb http://security.debian.org/ wheezy/updates main$'
    line='deb http://security.debian.org/ wheezy/updates main contrib non-free'

- name: Add contrib & non-free to security src
  lineinfile:
    dest=/etc/apt/sources.list
    backrefs=yes
    regexp='deb-src http://security.debian.org/ wheezy/updates main$'
    line='deb-src http://security.debian.org/ wheezy/updates main contrib non-free'

- name: Add contrib & non-free to updates
  lineinfile:
    dest=/etc/apt/sources.list
    backrefs=yes
    regexp='deb http://ftp.au.debian.org/debian/ wheezy-updates main$'
    line='deb http://ftp.au.debian.org/debian/ wheezy-updates main contrib non-free'

- name: Add contrib & non-free to updates
  lineinfile:
    dest=/etc/apt/sources.list
    backrefs=yes
    regexp='deb-src http://ftp.au.debian.org/debian/ wheezy-updates main$'
    line='deb-src http://ftp.au.debian.org/debian/ wheezy-updates main contrib non-free'
  
- name: Update APT package cache
  action: apt update_cache=yes

- name: Add multimedia keyring
  apt: pkg=deb-multimedia-keyring force=yes

