---
#
# Add commonly used repositories
#
- name: Add python-software-properties
  apt: pkg=python-software-properties force=yes update_cache=yes state=installed
  when: ansible_os_family == "Debian"

- name: Remove cdrom source
  lineinfile:
    dest=/etc/apt/sources.list
    backrefs=yes
    regexp='^deb cdrom'
    line='#deb cdrom:[Debian GNU/Linux 7.0.0 _Wheezy_ - Official amd64 CD Binary-1 20130504-14:44]/ wheezy main contrib non-free'
  notify: Update apt-get
#  command: /bin/sed -i 's/^deb cdrom/#deb cdrom/g' /etc/apt/sources.list
  
- name: Add multimedia {{ repo }} repository
  apt_repository: repo="deb http://www.deb-multimedia.org {{ repo }} main non-free"
  when: ansible_os_family == "Debian"

- name: Add contrib & non-free to main
  lineinfile:
    dest=/etc/apt/sources.list
    backrefs=yes
    regexp='deb http://ftp.au.debian.org/debian/ wheezy main$'
    line='deb http://ftp.au.debian.org/debian/ {{ repo }} main contrib non-free'
  when: ansible_os_family == "Debian"

- name: Add contrib & non-free to main src
  lineinfile:
    dest=/etc/apt/sources.list
    backrefs=yes
    regexp='deb-src http://ftp.au.debian.org/debian/ wheezy main$'
    line='deb-src http://ftp.au.debian.org/debian/ {{ repo }} main contrib non-free'
  when: ansible_os_family == "Debian"

- name: Add contrib & non-free to security
  lineinfile:
    dest=/etc/apt/sources.list
    backrefs=yes
    regexp='deb http://security.debian.org/ wheezy/updates main$'
    line='deb http://security.debian.org/ {{ repo }}/updates main contrib non-free'
  when: ansible_os_family == "Debian"

- name: Add contrib & non-free to security src
  lineinfile:
    dest=/etc/apt/sources.list
    backrefs=yes
    regexp='deb-src http://security.debian.org/ wheezy/updates main$'
    line='deb-src http://security.debian.org/ {{ repo }}/updates main contrib non-free'
  when: ansible_os_family == "Debian"

- name: Add contrib & non-free to updates
  lineinfile:
    dest=/etc/apt/sources.list
    backrefs=yes
    regexp='deb http://ftp.au.debian.org/debian/ wheezy-updates main$'
    line='deb http://ftp.au.debian.org/debian/ {{ repo }}-updates main contrib non-free'
  when: ansible_os_family == "Debian"

- name: Add contrib & non-free to updates
  lineinfile:
    dest=/etc/apt/sources.list
    backrefs=yes
    regexp='deb-src http://ftp.au.debian.org/debian/ wheezy-updates main$'
    line='deb-src http://ftp.au.debian.org/debian/ {{ repo }}-updates main contrib non-free'
  when: ansible_os_family == "Debian"
  
# - name: Update APT package cache
#   action: apt update_cache=yes

- name: Add multimedia keyring
  apt: pkg=deb-multimedia-keyring force=yes update_cache=yes
  when: ansible_os_family == "Debian"
  tags: focus