---
#
# Install Ruby backup utililty
#

- name: Install rsync
  apt:
    name: rsync
    state: present
  become: yes

- name: Install backup gem
  gem:
    name: backup
    state: present
    user_install: no
  become: yes

  # Doesn't work, some permissions problem
# - name: Generate a model
#   shell: backup generate:model --trigger website --databases="postgresql" --archives --splitter --notifiers=mail --compressor=gzip
#   become_user: deploy
