---
#
# Install Ruby backup utililty
#

- name: Install rsync
  apt:
    name: rsync
    state: present
  become: yes

# # Issues with installing
# - name: Install backup gem
#   shell: |
#     export RBENV_VERSION=2.3.7
#     {{ rbenv_root }}/shims/gem install backup
#   args:
#     creates: "{{ rbenv_root }}/shims/backup"
#   tags: focus


  # Doesn't work, some permissions problem
# - name: Generate a model
#   shell: backup generate:model --trigger website --databases="postgresql" --archives --splitter --notifiers=mail --compressor=gzip
#   become_user: deploy
