---
###
# Compresssion Utilities
###
- name: Install compression tools
  action: apt pkg={{ item }} state=present force=yes
  with_items:
    - unzip
    - zip
    - p7zip
    - gzip
    - pbzip2
    - bzip2
    - mscompress
    - xz-utils
    - dar
