---
#
# Emacs installer & config
#
# References
# http://www.plusastra.com/2012/11/installing-emacs-24-on-debian-wheezy.html
# http://www.emacswiki.org/emacs-es/EmacsSnapshotAndDebian
#

#
# Add org-mode pdf export support (942MB of disk space required!)
# Find a lighter alternative.
#  - texlive-latex-base, texlive-latex-recommended, texlive-latex-extra
#

- name: Install git
  apt: pkg=git-core

- name: Install emacs graphics libraries
  action: apt pkg=$item state=installed
  with_items:
    - libxaw7-dev
    - libxpm-dev
    - libpng12-dev
    - libtiff5-dev
    - libgif-dev
    - libjpeg8-dev
    - libgtk2.0-dev
    - libncurses5-dev

- name: Install GNU-Autotools
  action: apt pkg=$item state=installed
  with_items:
    - autoconf
    - automake
    - texinfo

- name: Clone repository
  command: git clone --depth 1 git://git.sv.gnu.org/emacs.git /tmp/emacs creates=/tmp/emacs 

- name: Generate emacs config
  action: command ./autogen.sh chdir=/tmp/emacs creates=/tmp/emacs/configure

- name: Run emacs configure
  action: command ./configure --prefix=/opt/emacs24 chdir=/tmp/emacs creates=/usr/local/bin/emacs

- name: Compile emacs24
  command: make -j $ansible_processor_cores chdir=/tmp/emacs creates=/usr/local/bin/emacs

- name: Install emacs24
  command: make install chdir=/tmp/emacs creates=/usr/local/bin/emacs

- name: Link emacs24
  command: ln -s /opt/emacs24/bin/emacs /usr/local/bin/emacs creates=/usr/local/bin/emacs

- name: Install window control
  apt: pkg=wmctrl state=present
