---
#
# gnome-do install & configure
#

- name: Install gnome-do
  apt: pkg=gnome-do

# Set gnome-do to hide on startup
- name: Copy gnome-do settings
  copy: src=common/files/gnome-do.tar dest=/home/$main_user/.gconf/apps
  
- name: Untar gnome-do settings
  command:
    mkdir -p /home/$main_user/.gconf/apps;tar xvf /home/$main_user/.gconf/apps/gnome-do chdir=/home/$main_user/.gconf/apps
    creates=/home/$main_user/.gconf/apps/gnome-do
