---
#
# gnome-do install & configure
#

- name: Install gnome-do
  apt: pkg=gnome-do

# Set gnome-do to hide on startup
- name: create directory
  file: path=/home/{{ ansible_ssh_user }}/.gconf/apps state=directory
  
- name: Copy gnome-do settings
  copy: src=common/files/gnome-do.tar dest=/home/{{ ansible_ssh_user }}/.gconf/apps

- name: Untar gnome-do settings
  command: tar xvf /home/{{ ansible_ssh_user }}/.gconf/apps/gnome-do.tar chdir=/home/{{ ansible_ssh_user }}/.gconf/apps creates=/home/{{ ansible_ssh_user }}/.gconf/apps/gnome-do
