---
#
# Kodi spotify plugin
#
- name: Download plugin
  command: wget {{ kodi_spotify }} chdir=/tmp creates=/home/{{ ansible_ssh_user }}/.kodi/addons/script.audio.spotimc

- name: mkdir
  shell: mkdir -p /home/{{ ansible_ssh_user }}/.kodi/addons creates=/home/{{ ansible_ssh_user }}/.kodi/addons/script.audio.spotimc

- name: untar plugin
  shell: unzip /tmp/script-audio-spotimc-1-0-beta5 -d /home/{{ ansible_ssh_user }}/.kodi/addons creates=/home/{{ ansible_ssh_user }}/.kodi/addons/script.audio.spotimc
