---
#
# Installs the latest libreoffice
#

- name: Remove old libreoffice
  action: apt pkg=$item state=removed purge=yes
  with_items:
    - libreoffice
    - libreoffice-base
    - libreoffice-base-core
    - libreoffice-calc
    - libreoffice-common
    - libreoffice-core
    - libreoffice-draw
    - libreoffice-emailmerge
    - libreoffice-evolution
    - libreoffice-filter-binfilter
    - libreoffice-filter-mobiledev
    - libreoffice-gnome
    - libreoffice-gtk
    - libreoffice-impress
    - libreoffice-java-common 
    - libreoffice-math
    - libreoffice-writer

- name: Download libreoffice debian 64bit version
  command: wget $libreoffice_download chdir=/tmp creates=/opt/libreoffice4.0

- name: Untar libreoffice
  shell: tar xvf LibreOffice*gz chdir=/tmp creates=/opt/libreoffice4.0

- name: Remove download
  shell: rm -fr /tmp/LibreOffice*gz creates=/opt/libreoffice4.0

- name: Move libreoffice download to /tmp/libreoffice
  shell: mv /tmp/LibreOffice* /tmp/libreoffice creates=/opt/libreoffice4.0

- name: Install libreoffice 4
  shell: /usr/bin/dpkg -i /tmp/libreoffice/DEBS/*.deb creates=/opt/libreoffice4.0

- name: Install libreoffice 4 menus
  shell: /usr/bin/dpkg -i /tmp/libreoffice/DEBS/desktop-integration/*.deb creates=/opt/libreoffice4.0
  
- name: clean up temp
  shell: rm -fr /tmp/libreoffice creates=/opt/libreoffice4.0