---
#
# Configure System Locale
#

- name: Setup System Locale as EN_AU.UTF-8
  lineinfile:
    dest: "/home/{{ ansible_ssh_user }}/.zshenv"
    state: present
    line: "{{ item.line }}"
  with_items:
    - { line: "export LANGUAGE=en_AU.UTF-8" }
    - { line: "export LC_ALL=en_AU.UTF-8" }
    - { line: "export LANG=en_AU.UTF-8" }
    - { line: "export LC_TYPE=en_AU.UTF-8" }
 # command: /usr/sbin/update-locale LANG="en_AU.UTF-8" LC_ALL="en_AU.UTF-8"
# - name: Setup System Locale as EN_AU.UTF-8
#   lineinfile:
#     dest: "/home/{{ ansible_ssh_user }}/.zshenv"
#     state: present
#     line: "{{ item.line }}"
#   with_items:
#     - { line: "export LANGUAGE=en_AU.UTF-8" }
#     - { line: "export LC_ALL=en_AU.UTF-8" }
#     - { line: "export LANG=en_AU.UTF-8" }
#     - { line: "export LC_TYPE=en_AU.UTF-8" }

- name: prepare locale info
  command: "{{ item }}"
  with_items:
    - echo locales locales/locales_to_be_generated multiselect     de_DE ISO-8859-1, de_DE.UTF-8 UTF-8, de_DE@euro ISO-8859-15, en_GB ISO-8859-1, en_GB.ISO-8859-15 ISO-8859-15, en_GB.UTF-8 UTF-8, en_US ISO-8859-1, en_US.ISO-8859-15 ISO-8859-15, en_US.UTF-8 UTF-8 en_AU.UTF-8 UTF-8 | debconf-set-selections
    - echo locales locales/default_environment_locale      select  en_AU.UTF-8 | debconf-set-selections
    - dpkg-reconfigure locales -f noninteractive
    - touch /root/.locales-updated
  when: ansible_distribution == 'Debian'
  args:
    creates: /root/.locales-updated

- name: set locales
  lineinfile:
    dest: /etc/locale.gen
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: "{{ item.state }}"
  with_items:
    - { regexp: "^#? ?{{ locale }} UTF-8", line: "{{ locale }} UTF-8", state: present }
  when: ansible_os_family == "Debian"
  notify: generate locales
  
# Undesirable as it overrides the locale.gen file and we loose other locales
# tasks file for locale 
# - name: set locale-gen file
#   template: src=locale-gen.j2 dest=/etc/locale.gen
#   when: ansible_os_family == "Debian"
#   notify: generate locales

- name: set locale
  become: yes
  template:
    src: common/templates/default-locale.j2
    dest: /etc/default/locale
  when: ansible_os_family == "Debian"
  notify: rebuild locales
