#
# Build the LTSP client
#
- name: Update image
  command: ltsp-update-image --config-nbd creates=/opt/ltsp/images/amd64.img

- name: Create ssh keys
  command: ltsp-update-sshkeys

# Configure nbd
- name: Configure network block device
  command: ltsp-config nbd-server
  notify: restart nbd

# Copy sources.list from server to LTSP
- name: Copy sources.list
  command: cp /etc/apt/sources.list /opt/ltsp/amd64/etc/apt/sources.list

