---
#
# LTSP - setup a Linux Terminal Server for PXE boot
#
# Only works in NFS mode.
#

- name: Install LTSP
  apt: pkg=ltsp-server force=yes

- name: Install epoptes
  apt: pkg=epoptes

- name: Add $user to epoptes
  action: command bash -c "for user in `ls /home`; do usermod -a -G epoptes $user; done"
  ignore_errors: yes
  
- name: Copy LTSP configuration accross
  copy: src=common/files/ltsp-build-client.conf dest=/etc/ltsp/ltsp-build-client.conf
  
# Sometimes there are some errors, but these can be safely ignored
- name: Build thin client
  action: command ltsp-build-client creates=/opt/ltsp/i386
  ignore_errors: yes

# Debian recommends we run LTSP in NFS mode, not NBD mode
- name: Add LTSP to exports
  lineinfile:
    dest=/etc/exports
    regexp="^/opt/ltsp"
    line="/opt/ltsp *(ro,no_root_squash,async,no_subtree_check)"
    backup=yes
    state=present
  notify: reload nfs
  
- name: Copy helper program over
  copy: src=common/files/ltsp-chroot dest=/usr/local/bin/ltsp-chroot mode=0755

- name: Copy over standard lts.conf config file
  copy: src=common/files/lts.conf dest=/var/lib/tftpboot/ltsp/i386/lts.conf


#
# Pulseaudio fixes
#
- name: Copy asound.conf
  copy: src=common/files/asound.conf dest=/etc/asound.conf backup=yes

- name: WORKAROUND - Copy Pulseaudio startup file
  copy: src="common/files/PulseAudio load module.desktop" dest="/tmp/PulseAudio load module.desktop"
  
- name: WORKAROUND - Load module-suspend-on-idle in users startup
  action: command bash -c "for user in `ls /home`; do cp '/tmp/PulseAudio load module.desktop' /home/$user/.config/autostart; done"
  ignore_errors: yes
  