# 10/10/2016 - Starting to use TVHeadend instead.

#
# Install PVR backend (mythtv)
#

# Issue: Still asks for password (Have sent an email to MLUG 10/05/13)
# echo -e '\n' | sudo DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical /usr/bin/apt-get --option Dpkg::Options::=--force-confold -q -y --force-yes install 'mythtv-backend'
# 
# As a workaround to this issue I copy over a script which uses 'expect' and answers the question automatically.

- name: Copy over script to run
  copy: src=common/files/install_mythtv-backend.sh dest=/tmp mode=0550

- name: Install Mythtv-backend
  action: command /tmp/install_mythtv-backend.sh creates=/usr/bin/mythbackend

- include: multimedia.yml
