---
#
# NodeJS installation
#

- name: Download installation script for Node 4.x
  action: command wget https://deb.nodesource.com/setup_4.x

- name: Run the setup
  action: command bash setup_4.x
  sudo: yes


# --------------------------------------------------------------------------------
# OLD
# --------------------------------------------------------------------------------

# # 2775 will set drwxrwsr-x which is what we want. The 2 at the front tells us that we want the 'sticky bit' on
# # the group
# - name: Change permissions so that users can add node_modules
#   file: path=/usr/local/lib/node_modules state=directory recurse=yes mode=2775

# - name: Set the main user as part of the staff group
#   user: name=$ansible_ssh_user group=staff

# # 
# # Install coffee-script & coffeelint for emacs coffee development
# #
# # Ref: 
# #  http://www.coffeelint.org/#usage 
# #  