---
#
# Main office applications
#

- include: common/tasks/add_repositories.yml

- include: common/tasks/java.yml
- include: common/tasks/libreoffice.yml
- include: common/tasks/dropbox.yml
- include: common/tasks/skype.yml
  
- name: Install office applications
  action: apt pkg=$item state=installed force=yes
  with_items:
    - pdfshuffler
    - xchm
    - okular           # PDF reader of choice
    - inkscape
    - gimp
    - keepassx
    - password-gorilla # Getting replaced by keepassx
    - gobby            # Collab. text editor
    - xchat
    - gwakeonlan       # Turning computers on around the office
    - ktorrent
    - wireshark
    - gparted
    - audacity
    - filezilla
    - chromium
    - wine
    - simple-scan
    - gnome-do
    - gkrellm
    - hotot            # twitter client
    - backintime-gnome # Backup

- name: Install compression tools
  action: apt pkg=$item state=installed force=yes
  with_items:
    - unzip
    - zip
    - p7zip
    - gzip
    - pbzip2
    - bzip2
    - mscompress
    - xz-utils
    - dar
    
- name: Install Debian specific applications
  action: apt pkg=$item state=installed
  when_string: $ansible_distribution == "Ubuntu"
  with_items:
    - firefox
    - thunderbird

- name: Install Debian specific applications
  action: apt pkg=$item state=installed
  when_string: $ansible_distribution == "Debian"
  with_items:
    - iceweasel
    - icedove

- name: Install flash
  apt: pkg=flashplugin-nonfree

- name: Install virtualbox
  apt: pkg=virtualbox-ose

