---
#
# Main office applications
#

- include: common/tasks/add_repositories.yml
- include: common/tasks/libreoffice.yml
- include: common/tasks/emacs.yml
  
- name: Install office applications
  action: apt pkg=$item state=installed force=yes
  with_items:
    - pdfshuffler
    - inkscape
    - gimp
    - keepassx
    - password-gorilla
    - gobby
    - xchat
    - gwakeonlan
    - ktorrent
    - wireshark
    - xchm
    - gparted
    - audacity
    - filezilla
    - chromium
    - wine
    - simple-scan
    - gnome-do
    - gkrellm

- name: Install Debian specific applications
  action: apt pkg=$item state=installed
  when_string: $ansible_distribution == "Ubuntu"
  with_items:
    - firefox
    - thunderbird

- name: Install Debian specific applications
  action: apt pkg=$item state=installed
  when_string: $ansible_distribution == "Debian"
  with_items:
    - iceweasel
    - icedove
  
- name: Install programming tools
  action: apt pkg=$item state=installed force=yes
  with_items:
    - vim
    - giggle
    - git
    - gitg
    - ghex
    - geany
    - pgadmin3

- name: Install flash
  apt: pkg=flashplugin-nonfree