---
#
# Main office applications
#

- include: add_repositories.yml

- include: java.yml
- include: libreoffice.yml
- include: dropbox.yml
- include: skype.yml
- include: mozilla.yml
  
- name: Install office applications
  action: apt pkg=$item state=installed force=yes
  with_items:
    - xclip
    - pdfshuffler
    - xchm
    - okular           # PDF reader of choice
    - inkscape
    - krita
    - gimp
    - gthumb          # Picture viewer & basic editor
    - keepassx
    - password-gorilla # Getting replaced by keepassx
    - gobby            # Collab. text editor
    - xchat
    - gwakeonlan       # Turning computers on around the office
    - ktorrent
    - wireshark
    - gparted
    - audacity
    - filezilla
    - chromium
    - wine
    - simple-scan
    - gnome-do
    - gkrellm
    - backintime-gnome # Backup
    - fsarchiver       # Backup system tool
    - gcalctool
    - file-roller      # Better integration with nautilus
    - cheese           # camera shot
      
- name: Install compression tools
  action: apt pkg=$item state=installed force=yes
  with_items:
    - unzip
    - zip
    - p7zip
    - gzip
    - pbzip2
    - bzip2
    - mscompress
    - xz-utils
    - dar

- name: Install flash
  apt: pkg=flashplugin-nonfree

- name: Install virtualbox
  apt: pkg=virtualbox-ose

