---
#
# Main office applications
#

- name: Install office applications
  action: apt pkg={{ item }} state=installed force=yes
  with_items:
    - xclip
    - pdfshuffler
    - xchm
    - okular                    # PDF reader of choice
    - inkscape
    - krita
    - gimp
    - gthumb                    # Picture viewer & basic editor
    - keepassx
    - password-gorilla          # Getting replaced by keepassx
    - gobby                     # Collab. text editor
    - xchat
    - gwakeonlan                # Turn computers on around the office
    - ktorrent
    - wireshark
    - gparted
    - audacity
    - filezilla
    - chromium
    - wine
    - simple-scan
    - gkrellm
    - backintime-gnome          # Backup
    - fsarchiver                # Backup system tool
    - file-roller               # Better integration with nautilus
    - cheese                    # camera shot
    #- unetbootin                # Create USB bootable distros (10/04/2015-N/A)
      
- name: Install compression tools
  action: apt pkg={{ item }} state=installed force=yes
  with_items:
    - unzip
    - zip
    - p7zip
    - gzip
    - pbzip2
    - bzip2
    - mscompress
    - xz-utils
    - dar

- name: Install flash
  apt: pkg=flashplugin-nonfree
  when: ansible_os_family == "Debian"

- name: Install virtualbox
  apt: pkg=virtualbox
  when: ansible_os_family == "Debian"
