---
#
# Install PostgreSQL
#

- name: Install postgresql requirements
  action: apt pkg=$item force=yes state=installed
  with_items:
    - python-psycopg2
    - libpq-dev

# https://coderwall.com/p/hdul2g - Update locale & timezone
# This is required so that PostgreSQL installs with UTF-8 support.
- name: set locale to $locale
  command: /usr/sbin/update-locale LANG=$locale LC_ALL=$locale

- name: Install postgresql
  action: apt pkg=postgresql force=yes state=installed

#
# Postgresql create user
#
- name: Create postgresql user
  postgresql_user: user=$db_user password=$db_passwd role_attr_flags=CREATEDB,SUPERUSER
  sudo_user: postgres

- name: Install nice postgresql tools
  action: apt pkg=$item force=yes state=installed
  with_items:
    - pgadmin3
    - phppgadmin
