---
#
# Install PostgreSQL
#

- name: Install postgresql
  action: apt pkg=$item force=yes state=installed
  with_items:
    - postgresql
    - python-psycopg2
    - libpq-dev

- name: Create postgresql user
  postgresql_user: user=$db_user password=$db_passwd role_attr_flags=CREATEDB,SUPERUSER
  sudo_user: postgres