---
#
# Programming tools and configuration
#  
- name: Install git
  apt: pkg=git state=installed

- include: common/tasks/emacs.yml
- include: common/tasks/rbenv.yml
- include: common/tasks/node.yml
- include: common/tasks/rails.yml

- name: Install programming tools
  action: apt pkg=$item state=installed force=yes
  with_items:
    - vim
    - giggle
    - gitg
    - ghex
    - geany
    - pgadmin3


- name: Install cheat
  action: command bash -c "/usr/local/bin/gem install cheat" creates=/usr/local/rbenv/shims/cheat

  
