---
#
# Install Ruby on Rails and other recommended gems
#
# This will be used on servers so keep this list of extra gems to a minimum.
#

- name: Install rails
  gem: name=rails state=present user_install=no
  sudo: yes

#
# Setup web apps area
#
- name: Set permissions on /srv
  file: path=/srv owner=root group=www-data mode=0775 state=directory
  sudo: yes

- name: Add main user to www-data group
  user: name=$main_user append=yes groups=www-data
  sudo: yes
  
#
# Extra rails projects requirements
# 
- name: Install libxslt-dev for nokogiri
  apt: pkg=libxslt-dev state=present
  sudo: yes
  

