---
#
# Install Ruby on Rails and other recommended gems
#
# This will be used on servers so keep this list of extra gems to a minimum.
#

# Done through bundle for the project instead of here

# - name: Install rails
#   gem:
#     name: rails
#     version: 5.2.0
#     state: present
#     user_install: no
#   become: yes

#
# Setup web apps area
#
- name: Set permissions on /var/www
  file: path=/var/www owner=root group=www-data mode=2775 state=directory
  become: yes

- name: Add main user to www-data group
  user: name={{ansible_ssh_user}} append=yes groups=www-data
  become: yes
  
#
# Extra rails projects requirements
# 
- name: Install libxslt-dev for nokogiri
  apt: name=libxslt-dev state=present
  become: yes

# For RefineryCMS & any image manipulation
- name: Install imagemagick
  apt: name=imagemagick state=present
  become: yes
  
# Install sqlite (just for testing)
- name: Install libsqlite3-dev for sqlite gem
  apt: name=libsqlite3-dev state=present
  become: yes

# Install bunder
- name: Install bundler using rbenv
  command: /usr/local/rbenv/shims/gem install bundler
  become: yes
  
