---
#
# Install Ruby on Rails and other recommended gems
#
# This will be used on servers so keep this list of extra gems to a minimum.
#
# Requires: rbenv.yml
# 

# You cannot use the gem module as the path will not pick it up if you have just installed rbenv
- name: Install rbenv-rehash
  action: command bash -c "/usr/local/bin/gem install rbenv-rehash" creates=/usr/local/rbenv/versions/$ruby_version/bin/rbenv-rehash

- name: Install rails
  action: command bash -c "/usr/local/bin/gem install rails" creates=/usr/local/rbenv/versions/$ruby_version/bin/rails

#
# Add phantomJS for testing
# 1. Download $phantomjs_download
- name: Download phantomjs
  command: wget $phantomjs_download chdir=/tmp creates=/opt/phantomjs

# 2. untar into /opt/phantomjs
- name: Untar phantomjs
  shell: tar xvf phantomjs*bz2 chdir=/tmp creates=/opt/phantomjs

- name: Remove download
  shell: rm -fr /tmp/phantomjs*bz2* creates=/opt/phantomjs

- name: Move phantomjs download to /opt/phantomjs
  shell: mv /tmp/phantomjs* /opt/phantomjs creates=/opt/phantomjs

# 3. link /opt/phantomjs/bin/phantomjs to /usr/local/bin
- name: Link phantomjs
  command: ln -s /opt/phantomjs/bin/phantomjs /usr/local/bin/phantomjs creates=/usr/local/bin/phantomjs