---
#
# System related tasks and tools
#

- name: Remove cdrom source
  command: /bin/sed -i 's/^deb cdrom/#deb cdrom/g' /etc/apt/sources.list

- name: Add multimedia testing repository
  apt_repository: repo='deb http://www.deb-multimedia.org testing main non-free'
  when_string: $ansible_distribution == "Debian"
  
- name: Update APT package cache
  action: apt update_cache=yes

- name: Install htop
  apt: pkg=htop

- name: Install screen
  apt: pkg=screen

- name: Install vim
  apt: pkg=vim force=yes

- name: SSH server
  apt: pkg=openssh-server

- name: Remote support
  apt: pkg=remmina
  apt: pkg=remmina-plugin-nx
  apt: pkg=remmina-plugin-vnc

