---
#
# System related tasks and tools
#

- include: add_repositories.yml
  
- name: Install system tools
  action: apt pkg=$item state=installed force=yes
  with_items:
    - htop
    - screen
    - vim
    - openssh-server
    - zsh
    - sysstat
    - mutt
    - mc
    - nethogs
    - ncdu
    - mosh # Awesome mobile ssh server/client
    - command-not-found # Package suggestion utility
    - bwm-ng            # bandwidth monitor for network & disk

- name: Update command-not-found
  action: command update-command-not-found
  when: ansible_os_family == "Debian"

- name: Remote support
  action: apt pkg=$item state=installed force=yes
  with_items:
    - remmina
    - remmina-plugin-nx
    - remmina-plugin-vnc

- name: Install expect for some installation scripts
  apt: pkg=expect force=yes

