---
#
# System related tasks and tools
#

- name: Install system tools
  action: apt pkg={{ item }} state=installed force=yes
  with_items:
    - htop
    - pwgen
    - screen
    - openssh-server
    - sysstat
    - ncdu              # Check disk usage per directory
    - mosh              # Awesome mobile ssh server/client
    - safe-rm           # Stop people typing 'rm -fr /'
    - molly-guard       # Save people from rebooting the wrong server.
    - expect            # Required for some installation scripts
    - mg                # emacs lite
    - pulseaudio-module-bluetooth # allows bluetooth connection via cmd line
    - git
    - flashplugin-nonfree
    
- name: Update command-not-found
  action: command update-command-not-found creates=/var/cache/apt/apt-file
  when: ansible_os_family == "Debian"

  # Move the following
    # Firmware
    # - firmware-linux-nonfree
