---
#
# System related tasks and tools
#

- include: common/tasks/add_repositories.yml
  
- name: Install system tools
  action: apt pkg=$item state=installed force=yes
  with_items:
    - htop
    - gkrellm
    - screen
    - vim
    - openssh-server
    - zsh
    - sysstat
    - mutt
    - mc
    - nethogs

- name: Remote support
  action: apt pkg=$item state=installed force=yes
  with_items:
    - remmina
    - remmina-plugin-nx
    - remmina-plugin-vnc

- name: Install expect for some installation scripts
  apt: pkg=expect force=yes