---
#
# XBMC install
#
- name: Install add-apt-repository
  apt: pkg=python-software-properties state=installed
    
- name: Add multimedia testing repository
  apt_repository: repo='deb http://www.deb-multimedia.org testing main non-free'
  when_string: $ansible_distribution == "Debian"

- name: Install latest xbmc
  apt: pkg=xbmc state=installed force=yes update_cache=yes 

#
# Install PVR backend (mythtv)
#

# Issue: Still asks for password (Have sent an email to MLUG 10/05/13)
# echo -e '\n' | sudo DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical /usr/bin/apt-get --option Dpkg::Options::=--force-confold -q -y --force-yes install 'mythtv-backend'
# 
# As a workaround to this issue I copy over a script which uses 'expect' and answers the question automatically.

- name: Copy over script to run
  copy: src=common/files/install_mythtv-backend.sh dest=/tmp mode=0550

- name: Install Mythtv-backend
  action: command /tmp/install_mythtv-backend.sh creates=/usr/bin/mythbackend

- include: multimedia.yml

#
# Setup shared XBMC library
#

# Setting up MySQL for shared library
- name: Install MySQL 5.5
  apt: pkg=mysql-server-5.5 force=yes state=installed

- name: Change the bind-address to servers static IP
  lineinfile:
    dest=/etc/mysql/my.cnf
    regexp="bind-address.*=.*127.0.0.1"
    backrefs=yes
    line="bind-address = {{ ansible_default_ipv4['address'] }}"
    backup=yes
    state=present
  notify: restart mysql
  
- name: Install python mysql module
  apt: pkg=python-mysqldb force=yes state=installed
  
- name: Create mysql user 'xbmc'
  mysql_user: name=xbmc password=xbmc priv=*.*:ALL state=present
  

# Setting up XBMC for shared library
- name: Create a storage1 directory for your first storage drive.
  file: path=/media/storage1 owner=$main_user group=$main_user mode=777 state=directory 
  
- name: Add /media/storage1 to NFS exports
  lineinfile:
    dest=/etc/exports
    regexp="/media/storage1"
    line="/media/storage1 *(rw,insecure)"
  notify: reload nfs
  
- name: Create settings dir for main user
  file: path=/home/$main_user/.xbmc owner=$main_user group=$main_user state=directory
  
- name: Create settings dir for main user
  file: path=/home/$main_user/.xbmc/userdata owner=$main_user group=$main_user state=directory
  
# This advancedsettings.xml file should be copied to the userdata dir of every XBMC install you want to sync with  
- name: Create an advancedsettings.xml file
  template:
    src=common/templates/advancedsettings.xml.j2
    dest=/home/$main_user/.xbmc/userdata/advancedsettings.xml mode=0644 force=no
  tags: focus

